// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aspnet_fishies.Data;

#nullable disable

namespace aspnet_fishies.Migrations
{
    [DbContext(typeof(FishDbContext))]
    [Migration("20250901145800_SeedFishData")]
    partial class SeedFishData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("aspnet_fishies.Models.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageWeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Seasonality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fish");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageWeightKg = 4.5m,
                            Description = "A popular fish found in the North Atlantic, valued for its flavor.",
                            Habitat = "Saltwater",
                            ImageUrl = "https://example.com/salmon.jpg",
                            LastUpdated = new DateTime(2025, 9, 1, 14, 57, 59, 747, DateTimeKind.Utc).AddTicks(3228),
                            Location = "North Atlantic Ocean",
                            MarketValue = 15.5m,
                            Name = "Atlantic Salmon",
                            ScientificName = "Salmo salar",
                            Seasonality = "Spring-Summer",
                            Status = "LeastConcern"
                        },
                        new
                        {
                            Id = 2,
                            AverageWeightKg = 250m,
                            Description = "Highly prized for sushi and sashimi, found in the Atlantic and Pacific.",
                            Habitat = "Saltwater",
                            ImageUrl = "https://example.com/tuna.jpg",
                            LastUpdated = new DateTime(2025, 9, 1, 14, 57, 59, 747, DateTimeKind.Utc).AddTicks(3304),
                            Location = "Atlantic & Pacific Oceans",
                            MarketValue = 200.0m,
                            Name = "Bluefin Tuna",
                            ScientificName = "Thunnus thynnus",
                            Seasonality = "Year-round",
                            Status = "Endangered"
                        },
                        new
                        {
                            Id = 3,
                            AverageWeightKg = 2.0m,
                            Description = "A freshwater fish known for its vibrant coloration and popularity among anglers.",
                            Habitat = "Freshwater",
                            ImageUrl = "https://example.com/trout.jpg",
                            LastUpdated = new DateTime(2025, 9, 1, 14, 57, 59, 747, DateTimeKind.Utc).AddTicks(3306),
                            Location = "North American rivers and lakes",
                            MarketValue = 12.0m,
                            Name = "Rainbow Trout",
                            ScientificName = "Oncorhynchus mykiss",
                            Seasonality = "Spring-Fall",
                            Status = "LeastConcern"
                        },
                        new
                        {
                            Id = 4,
                            AverageWeightKg = 1.5m,
                            Description = "A migratory fish with a complex life cycle, currently facing population decline.",
                            Habitat = "Brackish",
                            ImageUrl = "https://example.com/eel.jpg",
                            LastUpdated = new DateTime(2025, 9, 1, 14, 57, 59, 747, DateTimeKind.Utc).AddTicks(3308),
                            Location = "European coastal and inland waters",
                            MarketValue = 30.0m,
                            Name = "European Eel",
                            ScientificName = "Anguilla anguilla",
                            Seasonality = "Winter",
                            Status = "CriticallyEndangered"
                        },
                        new
                        {
                            Id = 5,
                            AverageWeightKg = 1.2m,
                            Description = "A widely farmed freshwater fish known for its mild flavor and affordability.",
                            Habitat = "Freshwater",
                            ImageUrl = "https://example.com/tilapia.jpg",
                            LastUpdated = new DateTime(2025, 9, 1, 14, 57, 59, 747, DateTimeKind.Utc).AddTicks(3310),
                            Location = "Global aquaculture farms",
                            MarketValue = 5.0m,
                            Name = "Tilapia",
                            ScientificName = "Oreochromis niloticus",
                            Seasonality = "Year-round",
                            Status = "LeastConcern"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
